version: '3.4'

services:
  dev-database:
    image: mysql:5.7
    container_name: ddialar-scoutbase
    environment:
      - MYSQL_DATABASE=scoutbase
      - MYSQL_USER=scoutbase
      - MYSQL_PASSWORD=scoutbase
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3306:3306
    volumes: 
      - ./configure-database:/docker-entrypoint-initdb.d:rw
      - type: volume
        source: ddialar-scoutbase-database
        target: /var/lib/mysql
        consistency: consistent

volumes: 
  ddialar-scoutbase-database:
    driver: local
    external: false